import {
    faBars,
    faBell,
    faBriefcase,
    faCar,
    faChevronDown,
    faCircleCheck,
    faClock,
    faEnvelope,
    faGear,
    faHeart,
    faHouse,
    faLaptop,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMobileScreen,
    faPlus,
    faRightFromBracket,
    faShieldHalved,
    faStore,
    faTag,
    faUser,
    faWrench,
} from "@fortawesome/free-solid-svg-icons";

import {
    faHeart as faHeartRegular,
    faUser as faUserRegular,
} from "@fortawesome/free-regular-svg-icons";

export {
    faBars,
    faBell,
    faBriefcase,
    faCar,
    faChevronDown,
    faCircleCheck,
    faClock,
    faEnvelope,
    faGear,
    faHeart,
    faHeartRegular,
    faHouse,
    faLaptop,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMobileScreen,
    faPlus,
    faRightFromBracket,
    faShieldHalved,
    faStore,
    faTag,
    faUser,
    faUserRegular,
    faWrench,
};