import {
    faBars,
    faBell,
    faBriefcase,
    faCar,
    faChevronDown,
    faCircleCheck,
    faClock,
    faCouch,
    faEnvelope,
    faGear,
    faHeart,
    faHouse,
    faLaptop,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMobileScreen,
    faPaw,
    faPlus,
    faRightFromBracket,
    faShirt,
    faShieldHalved,
    faStar,
    faStore,
    faTag,
    faToolbox,
    faUser,
    faWrench,


} from "@fortawesome/free-solid-svg-icons";


import {
    faHeart as faHeartRegular,
    faUser as faUserRegular,
} from "@fortawesome/free-regular-svg-icons";


export {
    faBars,
    faBell,
    faBriefcase,
    faCar,
    faChevronDown,
    faCircleCheck,
    faClock,
    faCouch,
    faEnvelope,
    faGear,
    faHeart,
    faHeartRegular,
    faHouse,
    faLaptop,
    faList,
    faLocationDot,
    faMagnifyingGlass,
    faMobileScreen,
    faPaw,
    faPlus,
    faRightFromBracket,
    faShirt,
    faShieldHalved,
    faStore,
    faTag,
    faToolbox,
    faUser,
    faUserRegular,
    faWrench,
    faStar,
};